// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAT6QT_uWQFDXjWi3Us-U4Gvj9QzGFfZU',
    appId: '1:375497404130:web:560f80ca218fe5307438bb',
    messagingSenderId: '375497404130',
    projectId: 'dating-39588',
    authDomain: 'dating-39588.firebaseapp.com',
    storageBucket: 'dating-39588.firebasestorage.app',
    measurementId: 'G-STKRWEYNHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEUYToMuuXQrmPTUiyzD99w8uUA3nsyzg',
    appId: '1:375497404130:android:be3a02491c395cfc7438bb',
    messagingSenderId: '375497404130',
    projectId: 'dating-39588',
    storageBucket: 'dating-39588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApSmiQNxWK8F7WF7pVdZTDTWMeqrlti4E',
    appId: '1:375497404130:ios:4d58a04bfb90e0367438bb',
    messagingSenderId: '375497404130',
    projectId: 'dating-39588',
    storageBucket: 'dating-39588.firebasestorage.app',
    iosClientId: '375497404130-i4aema74rknq9rapkl0l0rrshn7phlie.apps.googleusercontent.com',
    iosBundleId: 'com.example.dating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApSmiQNxWK8F7WF7pVdZTDTWMeqrlti4E',
    appId: '1:375497404130:ios:4d58a04bfb90e0367438bb',
    messagingSenderId: '375497404130',
    projectId: 'dating-39588',
    storageBucket: 'dating-39588.firebasestorage.app',
    iosClientId: '375497404130-i4aema74rknq9rapkl0l0rrshn7phlie.apps.googleusercontent.com',
    iosBundleId: 'com.example.dating',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAT6QT_uWQFDXjWi3Us-U4Gvj9QzGFfZU',
    appId: '1:375497404130:web:83fa7d5e942015047438bb',
    messagingSenderId: '375497404130',
    projectId: 'dating-39588',
    authDomain: 'dating-39588.firebaseapp.com',
    storageBucket: 'dating-39588.firebasestorage.app',
    measurementId: 'G-JEJ7METVGS',
  );
}
